apiVersion: batch/v1
kind: Job
metadata:
  name: mongosyncer-job
spec:
  template:
    spec:
      containers:
      - name: mongosyncer
        image: ghcr.io/romankudravcev/mongosyncer:latest
        envFrom:
        - configMapRef:
            name: mongosyncer-config
      restartPolicy: OnFailure
  backoffLimit: 2
