apiVersion: batch/v1
kind: Job
metadata:
  name: mongosyncer-job
spec:
  template:
    spec:
      containers:
      - name: mongosyncer
        image: ghcr.io/romankudravcev/mongosyncer:latest
        env:
        - name: MONGOSYNC_SOURCE
          value: "<your-source-uri>"
        - name: MONGOSYNC_TARGET
          value: "<your-target-uri>"
      restartPolicy: Never
  backoffLimit: 2

